using System.Collections.Generic;

namespace TPIH.Gecco.WPF.Helpers
{
    public class N3PR_Data
    {
        public const string DATA_FORMAT = "yyyy-MM-dd HH:mm:ss";
        public const string INT = "Int";
        public const string UINT = "UInt";
        public const string BOOL = "Bool";
        public const string PERCENTAGE = "%";

        public static List<string> TITLES = new List<string>();
        public static List<string> WHERE_SPLIT = new List<string>();

        // Data registers
        public static List<string> REG_NAMES = new List<string> {
        "STE_PTA",
        "STE_PTE",
        "STE_PTR",
        "STE_ASP",
        "STE_IPS",
        "STE_OPS",
        "STE_SPS",
        "STE_POW",
        "STE_ADB",
        "STE_ADC",
        "STE_BST",
        "STE_BSP",
        "STW_WPS",
        "STW_WDV",
        "STE_FCL",
        "STE_SDV",
        "STE_SBV",
        "STE_TER",
        "STE_TSR",
        "STE_PSR",
        "STE_TLP",
        "STE_SDS",
        "STE_SD1",
        "STE_SD2",
        "STE_SD3",
        "STE_SD4",
        "STE_SD5",
        "STE_SD6",
        "STE_SD7",
        "STE_SD8",
        "STE_RFV",
        "STA_PTS",
        "STA_RTR",
        "STA_DPS",
        "STA_SPT",
        "STA_LCK",
        "STA_PP1",
        "STA_PP2",
        "STA_PP3",
        "STA_PP4",
        "STA_PP5",
        "STA_PP6",
        "STA_PP7",
        "STA_PP8",
        "STA_PMP",
        "STA_PSP",
        "STA_MF1",
        "STA_MF2",
        "STA_MF3",
        "STA_MF4",
        "STA_MF5",
        "STA_MF6",
        "STA_RSV",
        "STA_FLM",
        "STA_TLP",
        "STA_RFV",
        "STA_FIN",
        "STA_FOU",
        "STB_PTS",
        "STB_RTR",
        "STB_DPS",
        "STB_SPT",
        "STB_LCK",
        "STB_PP1",
        "STB_PP2",
        "STB_PP3",
        "STB_PP4",
        "STB_PP5",
        "STB_PP6",
        "STB_PP7",
        "STB_PP8",
        "STB_PMP",
        "STB_PSP",
        "STB_MF1",
        "STB_MF2",
        "STB_MF3",
        "STB_MF4",
        "STB_MF5",
        "STB_MF6",
        "STB_RSV",
        "STB_FLM",
        "STB_TLP",
        "STB_RFV",
        "STB_FIN",
        "STB_FOU",
        "STC_PTS",
        "STC_RTR",
        "STC_DPS",
        "STC_SPT",
        "STC_LCK",
        "STC_PP1",
        "STC_PP2",
        "STC_PP3",
        "STC_PP4",
        "STC_PP5",
        "STC_PP6",
        "STC_PMP",
        "STC_PSP",
        "STC_MF1",
        "STC_MF2",
        "STC_MF3",
        "STC_MF4",
        "STC_MF5",
        "STC_MF6",
        "STC_RSV",
        "STC_FLM",
        "STC_TLP",
        "STC_RFV",
        "STC_FIN",
        "STC_FOU",
        "STD_PTS",
        "STD_RTR",
        "STD_DPS",
        "STD_SPT",
        "STD_LCK",
        "STD_PP1",
        "STD_PP2",
        "STD_PP3",
        "STD_PP4",
        "STD_PP5",
        "STD_PP6",
        "STD_PMP",
        "STD_PSP",
        "STD_MF1",
        "STD_MF2",
        "STD_MF3",
        "STD_MF4",
        "STD_MF5",
        "STD_MF6",
        "STD_RSV",
        "STD_FLM",
        "STD_TLP",
        "STD_RFV",
        "STD_FIN",
        "STD_FOU",
        "STH_TSH",
        "STH_TRH",
        "STH_TAH",
        "STH_FCV",
        "STH_ACT",
        "STH_DMN",
        "STH_STA",
        "SH1_ACT",
        "SH1_DMN",
        "SH2_ACT",
        "SH2_DMN",
        "SH3_ACT",
        "SH3_DMN",
        "SH4_ACT",
        "SH4_DMN",
        "SH5_ACT",
        "SH5_DMN",
        "SH6_ACT",
        "SH6_DMN",
        "STX_AIN",
        "STX_AOU",
        "SYS_STA"
        };
        public static List<string> REG_DESCRIPTION = new List<string> {
        "Ambient Dry Bulb - TaE",
        "Ecodry Outlet Temperature - TsE",
        "Ecodry Inlet Temperature - TrE",
        "Actual Set Point Temp.",
        "Ecodry Inlet Pressure - Pin",
        "Ecodry Outlet Pressure - Pout",
        "Fans Set Speed",
        "Total Fans Power",
        "Adiabatic Mode ",
        "Adiabatic Capacity",
        "Booster Mode",
        "Booster Percentage",
        "BWR Pump",
        "BWR Drain Valve",
        "Free Cooling Mode",
        "SSD Drain Valve",
        "SSD Bypass Valve",
        "SD Inlet Temperature - TeR",
        "SD Outlet Temperature - TsR",
        "Delivery Pressure - PsR",
        "Tank Level Percentage LtR",
        "SD Status",
        "SD Pump 1",
        "SD Pump 2",
        "SD Pump 3",
        "SD Pump 4",
        "SD Pump 5",
        "SD Pump 6",
        "SD Pump 7",
        "SD Pump 8",
        "Refill Valve",
        "Delivery Temperature - TsA",
        "Return Temperature - TrA",
        "Delivery Pressure - PsA",
        "Suction Pressure - PrA",
        "Pumps in Locked Configuration",
        "Pump 1",
        "Pump 2",
        "Pump 3",
        "Pump 4",
        "Pump 5",
        "Pump 6",
        "Pump 7",
        "Pump 8",
        "Available Pumps No.",
        "Pumps Set Speed",
        "Pump 1 Motor Frequency",
        "Pump 2 Motor Frequency",
        "Pump 3 Motor Frequency",
        "Pump 4 Motor Frequency",
        "Pump 5 Motor Frequency",
        "Pump 6 Motor Frequency",
        "Return Line Shut off Valve",
        "Flow Meter Reading",
        "Tank Level Percentage",
        "Refill Valve",
        "Filter In Pressure - Fina",
        "Filter Out Pressure - Fouta",
        "Delivery Temperature - TsB",
        "Return Temperature - TrB",
        "Delivery Pressure - PsB",
        "Suction Pressure - PrB",
        "Pumps in Locked Configuration",
        "Pump 1",
        "Pump 2",
        "Pump 3",
        "Pump 4",
        "Pump 5",
        "Pump 6",
        "Pump 7",
        "Pump 8",
        "Available Pumps No.",
        "Pumps Speed",
        "Pump 1 Motor Frequency",
        "Pump 2 Motor Frequency",
        "Pump 3 Motor Frequency",
        "Pump 4 Motor Frequency",
        "Pump 5 Motor Frequency",
        "Pump 6 Motor Frequency",
        "Return Line Shut off Valve",
        "Flow Meter Reading",
        "Tank Level Percentage",
        "Refill Valve",
        "Filter In Pressure - Finb",
        "Filter Out Pressure - Foutb",
        "Delivery Temperature - TsC",
        "Return Temperature - TrC",
        "Delivery Pressure - PsC",
        "Suction Pressure - PrC",
        "Pumps in Locked Configuration",
        "Pump 1",
        "Pump 2",
        "Pump 3",
        "Pump 4",
        "Pump 5",
        "Pump 6",
        "Available Pumps No.",
        "Pumps Speed",
        "Pump 1 Motor Frequency",
        "Pump 2 Motor Frequency",
        "Pump 3 Motor Frequency",
        "Pump 4 Motor Frequency",
        "Pump 5 Motor Frequency",
        "Pump 6 Motor Frequency",
        "Return Line Shut off Valve",
        "Flow Meter Reading",
        "Tank Level Percentage",
        "Refill Valve",
        "Filter In Pressure - FinC",
        "Filter Out Pressure - FoutC",
        "Delivery Temperature - TsD",
        "Return Temperature - TrD",
        "Delivery Pressure - PsD",
        "Suction Pressure - PrD",
        "Pumps in Locked Configuration",
        "Pump 1",
        "Pump 2",
        "Pump 3",
        "Pump 4",
        "Pump 5",
        "Pump 6",
        "Available Pumps No.",
        "Pumps Speed",
        "Pump 1 Motor Frequency",
        "Pump 2 Motor Frequency",
        "Pump 3 Motor Frequency",
        "Pump 4 Motor Frequency",
        "Pump 5 Motor Frequency",
        "Pump 6 Motor Frequency",
        "Return Line Shut off Valve",
        "Flow Meter Reading",
        "Tank Level Percentage",
        "Refill Valve",
        "Filter In Pressure - FinD",
        "Filter Out Pressure - FoutD",
        "Chiller Supply Temperature - TsH",
        "Chiller Return Temperature - TrH",
        "Chiller Ambient Temperature - TaH",
        "Free Cooling Valve Open/Closed",
        "System Actual Capacity",
        "System Demand Capacity",
        "Chiller System Status",
        "Actual Power",
        "Actual Chiller Demand",
        "Actual Power",
        "Actual Chiller Demand",
        "Actual Power",
        "Actual Chiller Demand",
        "Actual Power",
        "Actual Chiller Demand",
        "Actual Power",
        "Actual Chiller Demand",
        "Actual Power",
        "Actual Chiller Demand",
        "Analog Input",
        "Analog Output",
        "System Operation Status"
        };
        public static List<string> REG_MEASUNIT = new List<string> {
        "°C",
        "°C",
        "°C",
        "°C",
        "bar",
        "bar",
        "%",
        "kW",
        "false/true",
        "%",
        "false/true",
        "%",
        "false/true",
        "false/true",
        "false/true",
        "false/true",
        "false/true",
        "°C",
        "°C",
        "bar",
        "%",
        "Off/Starting/Forced/Running/Stopping",
        "false/true",
        "false/true",
        "false/true",
        "false/true",
        "false/true",
        "false/true",
        "false/true",
        "false/true",
        "false/true",
        "°C",
        "°C",
        "bar",
        "bar",
        "false/true",
        "false/true",
        "false/true",
        "false/true",
        "false/true",
        "false/true",
        "false/true",
        "false/true",
        "false/true",
        "Num",
        "Hz",
        "Hz",
        "Hz",
        "Hz",
        "Hz",
        "Hz",
        "Hz",
        "false/true",
        "m3/h",
        "%",
        "false/true",
        "bar",
        "bar",
        "°C",
        "°C",
        "bar",
        "bar",
        "false/true",
        "false/true",
        "false/true",
        "false/true",
        "false/true",
        "false/true",
        "false/true",
        "false/true",
        "false/true",
        "Num",
        "Hz",
        "Hz",
        "Hz",
        "Hz",
        "Hz",
        "Hz",
        "Hz",
        "false/true",
        "m3/h",
        "%",
        "false/true",
        "bar",
        "bar",
        "°C",
        "°C",
        "bar",
        "bar",
        "false/true",
        "false/true",
        "false/true",
        "false/true",
        "false/true",
        "false/true",
        "false/true",
        "Num",
        "Hz",
        "Hz",
        "Hz",
        "Hz",
        "Hz",
        "Hz",
        "Hz",
        "false/true",
        "m3/h",
        "%",
        "false/true",
        "bar",
        "bar",
        "°C",
        "°C",
        "bar",
        "bar",
        "false/true",
        "false/true",
        "false/true",
        "false/true",
        "false/true",
        "false/true",
        "false/true",
        "Num",
        "Hz",
        "Hz",
        "Hz",
        "Hz",
        "Hz",
        "Hz",
        "Hz",
        "false/true",
        "m3/h",
        "%",
        "false/true",
        "bar",
        "bar",
        "°C",
        "°C",
        "°C",
        "false/true",
        "%",
        "%",
        "Num",
        "%",
        "%",
        "%",
        "%",
        "%",
        "%",
        "%",
        "%",
        "%",
        "%",
        "%",
        "%",
        "--",
        "--",
        "--"
        };
        public static List<string> REG_TYPES = new List<string> {
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Bool",
        "Int",
        "Bool",
        "Int",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Int",
        "Int",
        "Int",
        "Int",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Bool",
        "Int",
        "Int",
        "Bool",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Bool",
        "Int",
        "Int",
        "Bool",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Bool",
        "Int",
        "Int",
        "Bool",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Bool",
        "Int",
        "Int",
        "Bool",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Bool",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Int",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool",
        "Bool"
        };
        public static List<string> REG_DIVFACTORS = new List<string> {
            "100",
            "100",
            "100",
            "100",
            "1000",
            "1000",
            "1",
            "100",
            "1",
            "10",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "100",
            "100",
            "100",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "100",
            "100",
            "100",
            "100",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "10",
            "10",
            "10",
            "10",
            "10",
            "10",
            "1",
            "100",
            "1",
            "1",
            "100",
            "100",
            "100",
            "100",
            "100",
            "100",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "10",
            "10",
            "10",
            "10",
            "10",
            "10",
            "1",
            "100",
            "1",
            "1",
            "100",
            "100",
            "100",
            "100",
            "100",
            "100",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "10",
            "10",
            "10",
            "10",
            "10",
            "10",
            "1",
            "100",
            "1",
            "1",
            "100",
            "100",
            "100",
            "100",
            "100",
            "100",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "10",
            "10",
            "10",
            "10",
            "10",
            "10",
            "1",
            "100",
            "1",
            "1",
            "100",
            "100",
            "100",
            "100",
            "100",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "1",
            "100",
            "1",
            "1"
        };

        // Alarms
        public static List<string> ALARM_WARNING_NAMES = new List<string> {
            "WNS_PBE",
            "WNS_PAE",
            "WNS_DRN",
            "WNS_FPD",
            "ALS_FPD",
            "WNS_ADB",
            "WNS_BST",
            "WNS_PSE",
            "ALS_PSE",
            "WNS_BWR",
            "WNF_HEC",
            "WBV_OPN",
            "WBV_NCL",
            "ABV_NOP",
            "A09_COM",
            "A09_BRK",
            "E09_COM",
            "W09_SL0",
            "W09_SL1",
            "W09_SL2",
            "W09_SL3",
            "W09_SL4",
            "W09_SL5",
            "W09_SL6",
            "W09_SL7",
            "W09_SL8",
            "W09_SL9",
            "W09_TSE",
            "A09_TAE",
            "A09_TSE",
            "W09_TRE",
            "A09_PIE",
            "A09_POE",
            "A09_LTE",
            "A09_PSE",
            "W09_PB1",
            "W09_PB2",
            "W09_PB3",
            "W09_PAE",
            "A09_PMP",
            "A10_COM",
            "A10_BRK",
            "E10_COM",
            "W10_SL0",
            "W10_SL1",
            "W10_SL2",
            "W10_SL3",
            "W10_SL4",
            "W10_SL5",
            "W10_SL6",
            "W10_SL7",
            "W10_SL8",
            "W10_SL9",
            "A10_PSE",
            "W10_PB1",
            "W10_PB2",
            "W10_PB3",
            "W10_PAE",
            "A10_PMP",
            "A11_COM",
            "A11_BRK",
            "E11_COM",
            "W11_SL0",
            "W11_SL1",
            "W11_SL2",
            "W11_SL3",
            "W11_SL4",
            "W11_SL5",
            "W11_SL6",
            "W11_SL7",
            "W11_SL8",
            "W11_SL9",
            "A11_PSE",
            "W11_PB1",
            "W11_PB2",
            "W11_PB3",
            "W11_PAE",
            "A11_PMP",
            "A12_COM",
            "A12_BRK",
            "E12_COM",
            "W12_SL0",
            "W12_SL1",
            "W12_SL2",
            "W12_SL3",
            "W12_SL4",
            "W12_SL5",
            "W12_SL6",
            "W12_SL7",
            "W12_SL8",
            "W12_SL9",
            "A12_PSE",
            "W12_PB1",
            "W12_PB2",
            "W12_PB3",
            "W12_PAE",
            "A12_PMP",
            "A01_COM",
            "E01_COM",
            "A01_LWL",
            "A01_LWS",
            "A01_LWR",
            "W01_REF",
            "W01_TSA",
            "W01_LPD",
            "A01_LPD",
            "A01_LSP",
            "W01_HPS",
            "W01_FPD",
            "A01_FPD",
            "W01_PSR",
            "A01_TSA",
            "W01_TRA",
            "A01_PSA",
            "A01_LTA",
            "A01_FIA",
            "A01_FOA",
            "A01_FMT",
            "A01_PP1",
            "A01_PP2",
            "A01_PP3",
            "A01_PP4",
            "A01_G11",
            "A01_G12",
            "A01_G13",
            "W01_G11",
            "W01_G12",
            "A01_G21",
            "A01_G22",
            "A01_G23",
            "W01_G21",
            "W01_G22",
            "A01_G31",
            "A01_G32",
            "A01_G33",
            "W01_G31",
            "W01_G32",
            "A01_G41",
            "A01_G42",
            "A01_G43",
            "W01_G41",
            "W01_G42",
            "A02_COM",
            "E02_COM",
            "A02_LWL",
            "A02_LWS",
            "A02_LWR",
            "W02_REF",
            "W02_TSB",
            "W02_LPD",
            "A02_LPD",
            "A02_LSP",
            "W02_HPS",
            "W02_FPD",
            "A02_FPD",
            "W02_PSR",
            "A02_TSB",
            "W02_TRB",
            "A02_PSB",
            "A02_LTB",
            "A02_FIB",
            "A02_FOB",
            "A02_FMT",
            "A02_PP1",
            "A02_PP2",
            "A02_PP3",
            "A02_PP4",
            "A02_G11",
            "A02_G12",
            "A02_G13",
            "W02_G11",
            "W02_G12",
            "A02_G21",
            "A02_G22",
            "A02_G23",
            "W02_G21",
            "W02_G22",
            "A02_G31",
            "A02_G32",
            "A02_G33",
            "W02_G31",
            "W02_G32",
            "A02_G41",
            "A02_G42",
            "A02_G43",
            "W02_G41",
            "W02_G42",
            "A03_COM",
            "A03_LWL",
            "A03_LWS",
            "A03_LWR",
            "W03_REF",
            "W03_TSC",
            "W03_LPD",
            "A03_LPD",
            "A03_LSP",
            "W03_HPS",
            "W03_FPD",
            "A03_FPD",
            "W03_PSR",
            "A03_TSC",
            "W03_TRC",
            "A03_PSC",
            "A03_LTC",
            "A03_FIC",
            "A03_FOC",
            "A03_FMT",
            "A03_PP1",
            "A03_PP2",
            "A03_PP3",
            "A03_PP4",
            "A05_COM",
            "A05_LWL",
            "A05_LWS",
            "A05_LWR",
            "W05_REF",
            "A05_LTE",
            "A05_LED",
            "A05_HED",
            "W05_PSR",
            "W05_RTS",
            "W05_TSR",
            "A05_TER",
            "A05_TSR",
            "A05_PSR",
            "A05_LTR",
            "A05_PP1",
            "A05_PP2",
            "A05_PP3",
            "A05_PP4",
            "A05_PP5",
            "A05_PP6",
            "A05_PP7",
            "A05_PP8",
            "A07_COM",
            "E07_COM",
            "W07_TSH",
            "A07_TSH",
            "A07_TRH",
            "A07_TAH",
            "A07_OFF",
            "A07_RMT",
            "A07_C11",
            "A07_C12",
            "A07_C13",
            "A07_C14",
            "A07_C15",
            "A07_C16",
            "A07_C21",
            "A07_C22",
            "A07_C23",
            "A07_C24",
            "A07_C25",
            "A07_C26",
            "A07_C31",
            "A07_C32",
            "A07_C33",
            "A07_C34",
            "A07_C35",
            "A07_C36",
            "A07_C41",
            "A07_C42",
            "A07_C43",
            "A07_C44",
            "A07_C45",
            "A07_C46",
            "PLC_CM1",
            "PLC_CM2",
            "PLC_CM3",
            "PLC_RED",
            "PLC_YLW"
        };

        public static List<string> ALARM_NAMES = new List<string>
        {
            "ALS_FPD",
            "ALS_PSE",
            "A09_COM",
            "A09_TAE",
            "A09_TSE",
            "A09_LTE",
            "A09_PSE",
            "A09_PMP",
            "A10_COM",
            "A10_PSE",
            "A10_PMP",
            "A11_COM",
            "A11_PSE",
            "A11_PMP",
            "A12_COM",
            "A12_PSE",
            "A12_PMP",
            "A01_TSA",
            "A01_FMT",
            "A01_PP1",
            "A01_PP2",
            "A01_PP3",
            "A01_PP4",
            "A01_G11",
            "A01_G12",
            "A01_G13",
            "A01_G21",
            "A01_G22",
            "A01_G23",
            "A01_G31",
            "A01_G32",
            "A01_G33",
            "A01_G41",
            "A01_G42",
            "A01_G43",
            "A02_COM",
            "A02_LWL",
            "A02_LWS",
            "A02_LWR",
            "A02_LPD",
            "A02_FPD",
            "A02_TSB",
            "A02_PSB",
            "A02_LTB",
            "A02_FMT",
            "A02_PP1",
            "A02_PP2",
            "A02_PP3",
            "A02_PP4",
            "A02_G11",
            "A02_G12",
            "A02_G13",
            "A02_G21",
            "A02_G22",
            "A02_G23",
            "A02_G31",
            "A02_G32",
            "A02_G33",
            "A02_G41",
            "A02_G42",
            "A02_G43",
            "A03_COM",
            "A03_LWL",
            "A03_LWS",
            "A03_LWR",
            "A03_LPD",
            "A03_FPD",
            "A03_TSC",
            "A03_PSC",
            "A03_LTC",
            "A03_FMT",
            "A03_PP1",
            "A03_PP2",
            "A03_PP3",
            "A03_PP4",
            "A05_COM",
            "A05_LWL",
            "A05_LWS",
            "A05_LWR",
            "A05_LTE",
            "A05_LED",
            "A05_TER",
            "A05_TSR",
            "A05_PSR",
            "A05_LTR",
            "A05_PP1",
            "A05_PP2",
            "A05_PP3",
            "A05_PP4",
            "A05_PP5",
            "A05_PP6",
            "A05_PP7",
            "A05_PP8",
            "A07_COM",
            "A07_TSH",
            "A07_TRH",
            "A07_TAH",
            "A07_C11",
            "A07_C12",
            "A07_C13",
            "A07_C14",
            "A07_C15",
            "A07_C16",
            "A07_C21",
            "A07_C22",
            "A07_C23",
            "A07_C24",
            "A07_C25",
            "A07_C26",
            "A07_C31",
            "A07_C32",
            "A07_C33",
            "A07_C34",
            "A07_C35",
            "A07_C36",
            "A07_C41",
            "A07_C42",
            "A07_C43",
            "A07_C44",
            "A07_C45",
            "A07_C46",
            "PLC_CM1",
            "PLC_CM2",
            "PLC_CM3",
            "PLC_RED",
            "A13_COM",
            "A13_PSE",
            "A13_PMP",
            "A14_COM",
            "A14_PSE",
            "A14_PMP",
            "A15_COM",
            "A15_PSE",
            "A15_PMP",
            "A16_COM",
            "A16_PSE",
            "A16_PMP",
            "A17_COM",
            "A17_PSE",
            "A17_PMP",
            "A18_COM",
            "A18_PSE",
            "A18_PMP"
        };

        public static List<string> ALARM_DESCRIPTION = new List<string> {
            "LOW BOOSTER SUPPLY PRESSURE [PBE1/PBE2/PBE3] WARNING",
            "LOW ADIABATIC SUPPLY PRESSURE [PAE] WARNING ",
            "SPRAY DRAINING FUNCTION WARNING",
            "HIGH FILTER PRESSURE DROP BWR",
            "HIGH FILTER PRESSURE DROP BWR",
            "ADIABATIC SPRAY INTERVAL SERVICE",
            "BOOSTER SPRAY INTERVAL SERVICE",
            "BWR LOW DELIVERY PRESSURE [PSE] WARNING",
            "BWR LOW DELIVERY PRESSURE [PSE] ALARM",
            "BWR PUMP INTERVAL SERVICE",
            "ECODRY HEAT EXCHANGER DE-FOULING",
            "ECODRY BYPASS VALVE OPEN",
            "ECODRY BYPASS VALVE NOT CLOSING",
            "ECODRY BYPASS VALVE NOT OPENING",
            "3PR-ECODRY ROW 1 TB9 COMMUNICATION ERROR",
            "ECODRY ROW 1 FAN BREAKER TRIPPED",
            "SERIAL COMMUNICATION ERROR ECODRY ROW 1, FAN ",
            "ECODRY ROW 1, FAN 1 ALARM",
            "ECODRY ROW 1, FAN 2 ALARM",
            "ECODRY ROW 1, FAN 3 ALARM",
            "ECODRY ROW 1, FAN 4 ALARM",
            "ECODRY ROW 1, FAN 5 ALARM",
            "ECODRY ROW 1, FAN 6 ALARM",
            "ECODRY ROW 1, FAN 7 ALARM",
            "ECODRY ROW 1, FAN 8 ALARM",
            "ECODRY ROW 1, FAN 9 ALARM",
            "ECODRY ROW 1, FAN 10 ALARM",
            "HIGH TSE TEMPERATURE WARNING",
            "ECODRY ROW 1, TEMPERATURE SENSOR TAE READING FAILURE",
            "ECODRY ROW 1, TEMPERATURE SENSOR TSE READING FAILURE",
            "ECODRY ROW 1, TEMPERATURE SENSOR TRE READING FAILURE",
            "ECODRY ROW 1, PRESSURE SENSOR PINE READING FAILURE",
            "ECODRY ROW 1, PRESSURE SENSOR POUTE READING FAILURE",
            "ECODRY ROW 1, LEVEL TRANSREDUCER LTE READING FAILURE",
            "ECODRY ROW 1, PRESSURE SENSOR PSE READING FAILURE",
            "ECODRY ROW 1, PRESSURE SENSOR PBE1 READING FAILURE",
            "ECODRY ROW 1, PRESSURE SENSOR PBE2 READING FAILURE",
            "ECODRY ROW 1, PRESSURE SENSOR PBE3 READING FAILURE",
            "ECODRY ROW 1, PRESSURE SENSOR PAE READING FAILURE",
            "BWR PUMP BREAKER FAULT ROW 1",
            "3PR-ECODRY ROW 2 TB9 COMMUNICATION ERROR",
            "ECODRY ROW 2 FAN BREAKER TRIPPED",
            "SERIAL COMMUNICATION ERROR ECODRY ROW 2, FAN ",
            "ECODRY ROW 2, FAN 1 ALARM",
            "ECODRY ROW 2, FAN 2 ALARM",
            "ECODRY ROW 2, FAN 3 ALARM",
            "ECODRY ROW 2, FAN 4 ALARM",
            "ECODRY ROW 2, FAN 5 ALARM",
            "ECODRY ROW 2, FAN 6 ALARM",
            "ECODRY ROW 2, FAN 7 ALARM",
            "ECODRY ROW 2, FAN 8 ALARM",
            "ECODRY ROW 2, FAN 9 ALARM",
            "ECODRY ROW 2, FAN 10 ALARM",
            "ECODRY ROW 2, PRESSURE SENSOR PSE READING FAILURE",
            "ECODRY ROW 2, PRESSURE SENSOR PBE1 READING FAILURE",
            "ECODRY ROW 2, PRESSURE SENSOR PBE2 READING FAILURE",
            "ECODRY ROW 2, PRESSURE SENSOR PBE3 READING FAILURE",
            "ECODRY ROW 2, PRESSURE SENSOR PAE READING FAILURE",
            "BWR PUMP BREAKER FAULT ROW 2",
            "3PR-ECODRY ROW 3 TB9 COMMUNICATION ERROR",
            "ECODRY ROW 3 FAN BREAKER TRIPPED",
            "SERIAL COMMUNICATION ERROR ECODRY ROW 3, FAN ",
            "ECODRY ROW 3, FAN 1 ALARM",
            "ECODRY ROW 3, FAN 2 ALARM",
            "ECODRY ROW 3, FAN 3 ALARM",
            "ECODRY ROW 3, FAN 4 ALARM",
            "ECODRY ROW 3, FAN 5 ALARM",
            "ECODRY ROW 3, FAN 6 ALARM",
            "ECODRY ROW 3, FAN 7 ALARM",
            "ECODRY ROW 3, FAN 8 ALARM",
            "ECODRY ROW 3, FAN 9 ALARM",
            "ECODRY ROW 3, FAN 10 ALARM",
            "ECODRY ROW 3, PRESSURE SENSOR PSE READING FAILURE",
            "ECODRY ROW 3, PRESSURE SENSOR PBE1 READING FAILURE",
            "ECODRY ROW 3, PRESSURE SENSOR PBE2 READING FAILURE",
            "ECODRY ROW 3, PRESSURE SENSOR PBE3 READING FAILURE",
            "ECODRY ROW 3, PRESSURE SENSOR PAE READING FAILURE",
            "BWR PUMP BREAKER FAULT ROW 3",
            "3PR-ECODRY ROW 4 TB9 COMMUNICATION ERROR",
            "ECODRY ROW 4 FAN BREAKER TRIPPED",
            "SERIAL COMMUNICATION ERROR ECODRY ROW 4, FAN ",
            "ECODRY ROW 4, FAN 1 ALARM",
            "ECODRY ROW 4, FAN 2 ALARM",
            "ECODRY ROW 4, FAN 3 ALARM",
            "ECODRY ROW 4, FAN 4 ALARM",
            "ECODRY ROW 4, FAN 5 ALARM",
            "ECODRY ROW 4, FAN 6 ALARM",
            "ECODRY ROW 4, FAN 7 ALARM",
            "ECODRY ROW 4, FAN 8 ALARM",
            "ECODRY ROW 4, FAN 9 ALARM",
            "ECODRY ROW 4, FAN 10 ALARM",
            "ECODRY ROW 4, PRESSURE SENSOR PSE READING FAILURE",
            "ECODRY ROW 4, PRESSURE SENSOR PBE1 READING FAILURE",
            "ECODRY ROW 4, PRESSURE SENSOR PBE2 READING FAILURE",
            "ECODRY ROW 4, PRESSURE SENSOR PBE3 READING FAILURE",
            "ECODRY ROW 4, PRESSURE SENSOR PAE READING FAILURE",
            "BWR PUMP BREAKER FAULT ROW 4",
            "3PR-CIRCUIT A TB9 COMMUNICATION ERROR",
            "SERIAL COMMUNICATION ERROR CIRCUIT A VFD PUMP",
            "LOW WATER LEVEL CIRCUIT A",
            "INSUFFICIENT WATER LEVEL TO START CIRCUIT A",
            "MAXIMUM NUMBER OF TANK LOW WATER LEVEL AUTO RESET EXCEEDED",
            "WATER REFILL TIME EXCEEDED IN TANK CIRCUIT A",
            "HIGH TSA TEMPERATURE WARNING",
            "LOW PUMP DIFFERENTIAL PRESSURE WARNING A",
            "LOW PUMP DIFFERENTIAL PRESSURE ALARM CIRCUIT A",
            "LOW PUMPS SUCTION PRESSURE ALARM CIRCUIT A",
            "HIGH PUMP PRESSURE WARNING CIRCUIT A",
            "HIGH FILTER PRESSURE DROP WARNING CIRCUIT A",
            "HIGH FILTER PRESSURE DROP ALARM CIRCUIT A",
            "PUMPS SERVICE WARNING CIRCUIT A",
            "TEMPERATURE SENSOR TSA READING FAILURE",
            "TEMPERATURE SENSOR TRA READING FAILURE",
            "PRESSURE SENSOR PSA READING FAILURE",
            "LEVEL TRANSDUCER LTA READING FAILURE",
            "PRESSURE SENSOR FINA READING FAILURE",
            "PRESSURE SENSOR FOUTA READING FAILURE",
            "FLOW METER FMTA READING FAILURE",
            "CIRCUIT A ON/OFF PUMP 1 BREAKER FAULT",
            "CIRCUIT A ON/OFF PUMP 2 BREAKER FAULT",
            "CIRCUIT A ON/OFF PUMP 3 BREAKER FAULT",
            "CIRCUIT A ON/OFF PUMP 4 BREAKER FAULT",
            "CIRCUIT A VFD PUMP 1 ALARM",
            "CIRCUIT A VFD PUMP 1 ALARM",
            "CIRCUIT A VFD PUMP 1 ALARM",
            "CIRCUIT A VFD PUMP 1 WARNING",
            "CIRCUIT A VFD PUMP 1 WARNING",
            "CIRCUIT A VFD PUMP 2 ALARM",
            "CIRCUIT A VFD PUMP 2 ALARM",
            "CIRCUIT A VFD PUMP 2 ALARM",
            "CIRCUIT A VFD PUMP 2 WARNING",
            "CIRCUIT A VFD PUMP 2 WARNING",
            "CIRCUIT A VFD PUMP 3 ALARM",
            "CIRCUIT A VFD PUMP 3 ALARM",
            "CIRCUIT A VFD PUMP 3 ALARM",
            "CIRCUIT A VFD PUMP 3 WARNING",
            "CIRCUIT A VFD PUMP 3 WARNING",
            "CIRCUIT A VFD PUMP 4 ALARM",
            "CIRCUIT A VFD PUMP 4 ALARM",
            "CIRCUIT A VFD PUMP 4 ALARM",
            "CIRCUIT A VFD PUMP 4 WARNING",
            "CIRCUIT A VFD PUMP 4 WARNING",
            "3PR-CIRCUIT B TB9 COMMUNICATION ERROR",
            "SERIAL COMMUNICATION ERROR CIRCUIT B VFD PUMP",
            "LOW WATER LEVEL CIRCUIT B",
            "INSUFFICIENT WATER LEVEL TO START CIRCUIT B",
            "MAXIMUM NUMBER OF TANK LOW WATER LEVEL AUTO RESET EXCEEDED",
            "WATER REFILL TIME EXCEEDED IN TANK CIRCUIT B",
            "HIGH TSB TEMPERATURE WARNING",
            "LOW PUMP DIFFERENTIAL PRESSURE WARNING CIRCUIT B",
            "LOW PUMP DIFFERENTIAL PRESSURE ALARM CIRCUIT B",
            "LOW PUMPS SUCTION PRESSURE ALARM CIRCUIT B",
            "HIGH PUMP PRESSURE WARNING CIRCUIT B",
            "HIGH FILTER PRESSURE DROP CIRCUIT B",
            "HIGH FILTER PRESSURE DROP ALARM CIRCUIT B",
            "PUMPS SERVICE WARNING CIRCUIT B",
            "TEMPERATURE SENSOR TSB READING FAILURE",
            "TEMPERATURE SENSOR TRB READING FAILURE",
            "PRESSURE SENSOR PSB READING FAILURE",
            "LEVEL TRANSDUCER LTB READING FAILURE",
            "PRESSURE SENSOR FINB READING FAILURE",
            "PRESSURE SENSOR FOUTB READING FAILURE",
            "FLOW METER FMTB READING FAILURE",
            "CIRCUIT B ON/OFF PUMP 1 BREAKER FAULT",
            "CIRCUIT B ON/OFF PUMP 2 BREAKER FAULT",
            "CIRCUIT B ON/OFF PUMP 3 BREAKER FAULT",
            "CIRCUIT B ON/OFF PUMP 4 BREAKER FAULT",
            "CIRCUIT B VFD PUMP 1 ALARM",
            "CIRCUIT B VFD PUMP 1 ALARM",
            "CIRCUIT B VFD PUMP 1 ALARM",
            "CIRCUIT B VFD PUMP 1 WARNING",
            "CIRCUIT B VFD PUMP 1 WARNING",
            "CIRCUIT B VFD pump 2 ALARM",
            "CIRCUIT B VFD pump 2 ALARM",
            "CIRCUIT B VFD pump 2 ALARM",
            "CIRCUIT B VFD pump 2 WARNING",
            "CIRCUIT B VFD pump 2 WARNING",
            "CIRCUIT B VFD pump 3 ALARM",
            "CIRCUIT B VFD pump 3 ALARM",
            "CIRCUIT B VFD pump 3 ALARM",
            "CIRCUIT B VFD pump 3 WARNING",
            "CIRCUIT B VFD pump 3 WARNING",
            "CIRCUIT B VFD pump 4 ALARM",
            "CIRCUIT B VFD pump 4 ALARM",
            "CIRCUIT B VFD pump 4 ALARM",
            "CIRCUIT B VFD pump 4 WARNING",
            "CIRCUIT B VFD pump 4 WARNING",
            "3PR-CIRCUIT C TB9 COMMUNICATION ERROR",
            "LOW WATER LEVEL CIRCUIT C",
            "INSUFFICIENT WATER LEVEL TO START CIRCUIT C",
            "MAXIMUM NUMBER OF TANK LOW WATER LEVEL AUTO RESET EXCEEDED",
            "WATER REFILL TIME EXCEEDED IN TANK CIRCUIT C",
            "HIGH TSC TEMPERATURE WARNING",
            "LOW PUMP DIFFERENTIAL PRESSURE WARNING CIRCUIT C",
            "LOW PUMP DIFFERENTIAL PRESSURE ALARM CIRCUIT C",
            "LOW PUMPS SUCTION PRESSURE ALARM CIRCUIT C",
            "HIGH PUMP PRESSURE WARNING CIRCUIT C",
            "HIGH FILTER PRESSURE DROP CIRCUIT C",
            "HIGH FILTER PRESSURE DROP ALARM CIRCUIT C",
            "PUMPS SERVICE WARNING CIRCUIT C",
            "TEMPERATURE SENSOR TSC READING FAILURE",
            "TEMPERATURE SENSOR TRC READING FAILURE",
            "PRESSURE SENSOR PSC READING FAILURE",
            "LEVEL TRANSDUCER LTC READING FAILURE",
            "PRESSURE SENSOR FINC READING FAILURE",
            "PRESSURE SENSOR FOUTC READING FAILURE",
            "FLOW METER FMTC READING FAILURE",
            "CIRCUIT C ON/OFF PUMP 1 BREAKER FAULT",
            "CIRCUIT C ON/OFF PUMP 2 BREAKER FAULT",
            "CIRCUIT C ON/OFF PUMP 3 BREAKER FAULT",
            "CIRCUIT C ON/OFF PUMP 4 BREAKER FAULT",
            "3PR-CIRCUIT SDP TB9 COMMUNICATION ERROR",
            "LOW WATER LEVEL CIRCUIT SDP",
            "INSUFFICIENT WATER LEVEL TO START CIRCUIT SDP",
            "MAXIMUM NUMBER OF TANK LOW WATER LEVEL AUTO RESET EXCEEDED",
            "WATER REFILL TIME EXCEEDED IN TANK CIRCUIT SDP",
            "LOW ECODRY OUTLET TEMPERATURE TER",
            "LOW ECODRY DELTA P",
            "HIGH ECODRY DELTA P",
            "PUMPS SERVICE WARNING CIRCUIT SDP",
            "PUMPS ROTATION WARNING CIRCUIT SDP",
            "HIGH TSR TEMPERATURE WARNING",
            "TEMPERATURE SENSOR TER READING FAILURE",
            "TEMPERATURE SENSOR TSR READING FAILURE",
            "PRESSURE SENSOR PSR READING FAILURE",
            "LEVEL TRANSREDUCER LTR READING FAILURE",
            "SDP ON/OFF PUMP 1 BREAKER FAULT",
            "SDP ON/OFF PUMP 2 BREAKER FAULT",
            "SDP ON/OFF PUMP 3 BREAKER FAULT",
            "SDP ON/OFF PUMP 4 BREAKER FAULT",
            "SDP ON/OFF PUMP 5 BREAKER FAULT",
            "SDP ON/OFF PUMP 6 BREAKER FAULT",
            "SDP ON/OFF PUMP 7 BREAKER FAULT",
            "SDP ON/OFF PUMP 8 BREAKER FAULT",
            "3PR-CENTRAL CHILLER TB9 COMMUNICATION ERROR",
            "SERIAL COMMUNICATION ERROR CENTRAL CHILLER",
            "HIGH TSH TEMPERATURE WARNING",
            "TEMPERATURE SENSOR TSH READING FAILURE",
            "TEMPERATURE SENSOR TRH READING FAILURE",
            "TEMPERATURE SENSOR TAH READING FAILURE",
            "STATUS IS OFF FOR CHILLER",
            "CONFIG IS NOT IN REMOTE CONTROL FOR CHILLER",
            "CENTRAL CHILLER 1 ALARM 1",
            "CENTRAL CHILLER 1 ALARM 2",
            "CENTRAL CHILLER 1 ALARM 3",
            "CENTRAL CHILLER 1 ALARM 4",
            "CENTRAL CHILLER 1 ALARM 5",
            "CENTRAL CHILLER 1 ALARM 6",
            "CENTRAL CHILLER 2 ALARM 1",
            "CENTRAL CHILLER 2 ALARM 2",
            "CENTRAL CHILLER 2 ALARM 3",
            "CENTRAL CHILLER 2 ALARM 4",
            "CENTRAL CHILLER 2 ALARM 5",
            "CENTRAL CHILLER 2 ALARM 6",
            "CENTRAL CHILLER 3 ALARM 1",
            "CENTRAL CHILLER 3 ALARM 2",
            "CENTRAL CHILLER 3 ALARM 3",
            "CENTRAL CHILLER 3 ALARM 4",
            "CENTRAL CHILLER 3 ALARM 5",
            "CENTRAL CHILLER 3 ALARM 6",
            "CENTRAL CHILLER 4 ALARM 1",
            "CENTRAL CHILLER 4 ALARM 2",
            "CENTRAL CHILLER 4 ALARM 3",
            "CENTRAL CHILLER 4 ALARM 4",
            "CENTRAL CHILLER 4 ALARM 5",
            "CENTRAL CHILLER 4 ALARM 6",
            "COMMUNICATION MODULE CM1 INITIALIZATION FAILURE",
            "COMMUNICATION MODULE CM2 INITIALIZATION FAILURE",
            "COMMUNICATION MODULE CM3 INITIALIZATION FAILURE",
            "SYSTEM IN ALARM OR FAULT",
            "SYSTEM IN WARNING"
        };
        public static List<string> ALARM_TYPES = new List<string> {
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "ALARM",
            "WARNING",
            "WARNING",
            "WARNING",
            "ALARM",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "STOP",
            "ALARM",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "ALARM",
            "ALARM",
            "WARNING",
            "WARNING",
            "WARNING",
            "ALARM",
            "ALARM",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "ALARM",
            "ALARM",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "ALARM",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "ALARM",
            "ALARM",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "ALARM",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "ALARM",
            "ALARM",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "ALARM",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "ALARM",
            "STOP",
            "WARNING",
            "STOP",
            "STOP",
            "STOP",
            "WARNING",
            "WARNING",
            "WARNING",
            "STOP",
            "WARNING",
            "WARNING",
            "WARNING",
            "STOP",
            "WARNING",
            "ALARM",
            "WARNING",
            "STOP",
            "STOP",
            "WARNING",
            "WARNING",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "WARNING",
            "WARNING",
            "ALARM",
            "ALARM",
            "ALARM",
            "WARNING",
            "WARNING",
            "ALARM",
            "ALARM",
            "ALARM",
            "WARNING",
            "WARNING",
            "ALARM",
            "ALARM",
            "ALARM",
            "WARNING",
            "WARNING",
            "ALARM",
            "WARNING",
            "ALARM",
            "ALARM",
            "ALARM",
            "WARNING",
            "WARNING",
            "WARNING",
            "ALARM",
            "WARNING",
            "WARNING",
            "WARNING",
            "ALARM",
            "WARNING",
            "ALARM",
            "WARNING",
            "ALARM",
            "ALARM",
            "WARNING",
            "WARNING",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "WARNING",
            "WARNING",
            "ALARM",
            "ALARM",
            "ALARM",
            "WARNING",
            "WARNING",
            "ALARM",
            "ALARM",
            "ALARM",
            "WARNING",
            "WARNING",
            "ALARM",
            "ALARM",
            "ALARM",
            "WARNING",
            "WARNING",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "WARNING",
            "WARNING",
            "WARNING",
            "ALARM",
            "WARNING",
            "WARNING",
            "WARNING",
            "ALARM",
            "WARNING",
            "ALARM",
            "WARNING",
            "ALARM",
            "ALARM",
            "WARNING",
            "WARNING",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "WARNING",
            "ALARM",
            "ALARM",
            "WARNING",
            "WARNING",
            "WARNING",
            "WARNING",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "WARNING",
            "WARNING",
            "ALARM",
            "ALARM",
            "ALARM",
            "WARNING",
            "WARNING",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "ALARM",
            "WARNING",
        };
    }
}
